---
title: Предупреждение компилятора (уровень 4) C4571
ms.date: 11/04/2016
f1_keywords:
- C4571
helpviewer_keywords:
- C4571
ms.assetid: 07aa17bd-b15c-4266-824c-57cc445e8edd
ms.openlocfilehash: 92164bf297a44871897b6c6150eb54f8c5ccf3cc
ms.sourcegitcommit: 6052185696adca270bc9bdbec45a626dd89cdcdd
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/31/2018
ms.locfileid: "50431061"
---
# <a name="compiler-warning-level-4-c4571"></a>Предупреждение компилятора (уровень 4) C4571

Сведению: семантика catch(...) изменилась Visual C++ 7.1; структурированные исключения (SEH) более не перехватываются

Предупреждение C4571 создается для каждого блока catch(...) при компиляции с параметром **/EHs**.

При компиляции с параметром **/EHs**, блок catch(...) не будет перехватывать структурированное исключение (деление на ноль или пустым указателем, например); catch(...) будет обнаруживать только явным образом в случае исключения C++.  Дополнительные сведения см. в разделе [Обработка исключений](../../cpp/exception-handling-in-visual-cpp.md).

Это предупреждение отключено по умолчанию.  Включите это предупреждение, чтобы убедиться, что при компиляции с параметром **/EHs** блоки catch (...) не будут перехватывать структурированные исключения.  Подробнее: [Выключенные по умолчанию предупреждения компилятора](../../preprocessor/compiler-warnings-that-are-off-by-default.md) .

C4571 можно устранить одним из следующих способов:

- Скомпилируйте с **/EHa** Если вы все равно хотите блоки catch(...) перехватывать структурированные исключения.

- Не включайте C4571, если требуется запретить блоки catch(...) перехватывать структурированные исключения, но вы по-прежнему хотите использовать блоки catch(...).  Всегда можно просмотреть с помощью ключевых слов обработки структурированных исключений структурированные исключения (**__try**, **__except**, и **__finally**).  Но помните, что при компиляции **/EHs** деструкторы будет вызываться только при возникновении исключения C++, а не в том случае, когда происходит исключение SEH.

- Замените блок catch(...) блоки catch для определенных исключений C++ и при необходимости добавьте структурированной обработки вокруг обработки исключений C++ исключений (**__try**, **__except**, и **_ _finally**).  См. в разделе [структурированная обработка исключений (C/C++)](../../cpp/structured-exception-handling-c-cpp.md) Дополнительные сведения.

См. в разделе [/EH (модель обработки исключений)](../../build/reference/eh-exception-handling-model.md) Дополнительные сведения.

## <a name="example"></a>Пример

В следующем примере возникает предупреждение C4571.

```
// C4571.cpp
// compile with: /EHs /W4 /c
#pragma warning(default : 4571)
int main() {
   try {
      int i = 0, j = 1;
      j /= i;   // this will throw a SE (divide by zero)
   }
   catch(...) {}   // C4571 warning
}
```