---
title: C26110
ms.date: 10/01/2019
ms.topic: reference
f1_keywords:
- C26110
helpviewer_keywords:
- C26110
ms.assetid: d82b79ec-6d7f-438b-bd6a-da874a3e08e5
ms.openlocfilehash: 37c025f4a55f292c8fa0259239c64dab06f4e4b0
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/17/2020
ms.locfileid: "79466953"
---
# <a name="c26110"></a>C26110

> предупреждение C26110: вызывающая сторона не удерживает блокировку \<> блокировки перед вызовом функции \<Func >.

Если требуется блокировка, обязательно выясните, должна ли сама функция или ее вызывающая сторона получить блокировку. Предупреждение C26110 выдается при нарушении `_Requires_lock_held_` аннотации или других заметок, связанных с блокировкой. Дополнительные сведения см. в разделе [Аннотирование режима блокировки](annotating-locking-behavior.md) .

## <a name="example"></a>Пример

В следующем примере создается предупреждение C26110, так как Аннотация `_Requires_lock_held_` on Function `LockRequired` указывает, что вызывающий объект `LockRequired` должен получить блокировку перед вызовом `LockRequired`. Без этой заметки `LockRequired` должен получить блокировку до того, как она будет обращаться к любым общим данным, защищенным блокировкой.

```cpp
typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_held_(p->cs)

void LockRequired(DATA* p)
{
    p->d = 0;
}

void LockNotHeld(DATA* p)
{
    LockRequired(p); // Warning C26110
}
```
